[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "disguise-designer-d3blobgen"
version = "0.1.0"
description = "Blob generation helper for d3 python plugin"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

