[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "disguise-designer-d3blobgen"
version = "0.1.0"
description = "Blob generation helper for d3 python plugin"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.15",
    "pydantic>=2.11.7",
    "requests>=2.32.5",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
d3blobgen = ["py.typed", "scripts/d3.pyi"]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.1.0",
]

