import ast
import inspect
import functools
import requests
import aiohttp
import textwrap
import json
from dataclasses import dataclass
from pydantic import BaseModel, Field, field_validator
from typing import TypeVar, ParamSpec, Callable, Any, Generic, DefaultDict, Type, get_type_hints
import typing_extensions
from types import FrameType, ModuleType
from collections import defaultdict


###############################################################################
# Plugin response types
D3_PLUGIN_ENDPOINT = "api/session/python/execute"

class PluginStatusDetail(BaseModel):
    type_url: str
    value: str

class PluginStatus(BaseModel):
    code: int = Field(description="Return code of plugin API call. 0 if good.")
    message: str = Field(description="Message from plugin API call.")
    details: list[PluginStatusDetail]

RetType = typing_extensions.TypeVar("RetType", default=Any)
RetCastType = TypeVar("RetCastType")

@dataclass
class PluginError(Exception):
    status: PluginStatus

    def __str__(self) -> str:
        details_str = ""
        if self.status.details:
            details_list = "\n".join([f"  - {d.type_url}: {d.value}" for d in self.status.details])
            details_str = f"\nDetails:\n{details_list}"
        return f"{Exception.__str__(self)}\nPluginError (code {self.status.code}): {self.status.message}{details_str}"

class PluginResponse(BaseModel, Generic[RetType]):
    status: PluginStatus = Field(description="Status of plugin API call.")
    d3Log: str | None = Field(default=None, description="The D3 log field captures the console log for the time the Python script is executing, recording any output generated by running a Python command, including the time taken to execute the Python command. As this captures the Designer console output, it is possible other threads may write to this output during this period causing additional irrelevant output.")
    pythonLog: str | None = Field(default=None, description="This output field is the pure Python output, recording any print statements or warnings occurring during the execution of the script. This output will also appear in the d3Log field, however, it may be mixed with other application output.")
    returnValue: RetType = Field(description="Return value of python plugin execution")

    @field_validator("returnValue", mode="before")
    @classmethod
    def parse_returnValue(cls, v):
        if isinstance(v, str):
            if v == "null":
                return None
            else:
                return json.loads(v)
        return v
    
    def returnCastValue(self, castType: Type[RetCastType]) -> RetCastType:
        """
        When `RetType` is `Any` by default, the typed return value
        can be retrieved by this method.
        """
        if not isinstance(self.returnValue, castType):
            raise ValueError(
                f"returnValue is not of type {castType.__name__}: {type(self.returnValue).__name__}"
            )
        return self.returnValue


###############################################################################
# import package helpers
def find_packages_in_current_file(caller_stack:int = 1) -> list[str]:
    """Find all import statements in the caller's file by inspecting the call stack.

    This function walks up the call stack to find the module where it was called from,
    then parses that module's source code to extract all import statements.

    Args:
        caller_stack: Number of frames to go up the call stack. Default is 1 (immediate caller).
                     Use higher values to inspect files further up the call chain.

    Returns:
        Sorted list of unique import statement strings (e.g., "import ast", "from pathlib import Path").

    Filters applied:
        - Excludes imports inside `if TYPE_CHECKING:` blocks
        - Excludes imports of this function itself to avoid circular references
    """
    # Get the this file frame
    current_frame: FrameType | None = inspect.currentframe()
    if not current_frame:
        return []

    # Get the caller's frame (file where this function is called)
    caller_frame: FrameType | None = current_frame
    for i in range(caller_stack):
        if not caller_frame.f_back:
            return []
        caller_frame = caller_frame.f_back

    if not caller_frame:
        return []

    modules: ModuleType | None = inspect.getmodule(caller_frame)
    if not modules:
        return []

    source: str = inspect.getsource(modules)
    source_lines: list[str] = source.splitlines()

    # Parse the source code
    tree = ast.parse(source)

    # Get the name of this function to filter it out
    # For example, we don't want `from core import find_packages_in_current_file`
    function_name: str = current_frame.f_code.co_name
    # Skip any package from d3blobgen
    d3blobgen_package_name: str = "d3blobgen"
    # typing not supported in python2.7
    typing_package_name: str = "typing"

    def is_type_checking_block(node: ast.If) -> bool:
        """Check if an if statement is 'if TYPE_CHECKING:'"""
        return isinstance(node.test, ast.Name) and node.test.id == "TYPE_CHECKING"

    imports: list[str] = []
    for node in tree.body:
        # Skip TYPE_CHECKING blocks entirely
        if isinstance(node, ast.If) and is_type_checking_block(node):
            continue

        if isinstance(node, ast.Import):
            # Handle multi-line imports by capturing from lineno to end_lineno
            start_line = node.lineno - 1
            end_line = node.end_lineno if node.end_lineno else node.lineno
            line_text = " ".join([line.strip().strip("\\") for line in source_lines[start_line:end_line]]).strip()
            imported_modules: list[str] = [alias.name for alias in node.names]
            # Skip imports that include d3blobgen
            if any(d3blobgen_package_name in module for module in imported_modules):
                continue
            if any(typing_package_name in module for module in imported_modules):
                continue

            imports.append(line_text)
        elif isinstance(node, ast.ImportFrom):
            imported_module: str | None = node.module
            imported_names: list[str] = [alias.name for alias in node.names]
            # Skip imports that include d3blobgen
            if imported_module:
                if d3blobgen_package_name in imported_module:
                    continue
                elif typing_package_name in imported_module:
                    continue
            # Skip imports that include this function itself
            if function_name in imported_names:
                continue
            # Handle multi-line imports by capturing from lineno to end_lineno
            start_line = node.lineno - 1
            end_line = node.end_lineno if node.end_lineno else node.lineno
            line_text: str = " ".join([line.strip().strip("\\") for line in source_lines[start_line:end_line]]).strip()
            imports.append(line_text)

    return sorted(set(imports))


###############################################################################
# Plugin function related implementations
class FunctionInfo(BaseModel):
    """Container for parsed function information extracted from Python source code.
    
    This model holds all the essential components of a function after parsing,
    including its complete definition, name, body statements, and argument list.
    """
    blob: str = Field(description="full body of function blob without decorator (Function definition + body)")
    blob_py27: str =  Field(description="full body of function blob without decorator in python2.7 format (Function definition + body)")
    name: str = Field(description="name of extracted function")
    body: str = Field(description="body of extracted function in str format")
    body_py27: str = Field(description="body of extracted function in python2.7 str format")
    args: list[str] = Field(default=[], description="list of arguments from extracted function")

def convert_ann_assign_to_assign(ann_assign_node: ast.AnnAssign) -> ast.Assign|None:
    """Convert an annotated assignment node to a regular assignment node.
    
    This function transforms type-annotated variable assignments (e.g., 'x: int = 5') 
    into regular assignments (e.g., 'x = 5') for Python 2.7 compatibility.
    
    Args:
        ann_assign_node: AST node representing an annotated assignment.
        
    Returns:
        ast.Assign node without type annotation, or None if no value is assigned.
    """
    if ann_assign_node.value is None:
        return None
    
    return ast.Assign(
        targets=[ann_assign_node.target],
        value=ann_assign_node.value,
        lineno = ann_assign_node.lineno,
        col_offset = ann_assign_node.col_offset)

class FastRemoveTypeHints(ast.NodeTransformer):
    """AST transformer to remove type hints from Python code for 2.7 compatibility."""
    
    def visit_AnnAssign(self, node):
        """Transform annotated assignment nodes to regular assignment nodes.
        
        Args:
            node: The annotated assignment AST node to transform.
            
        Returns:
            Regular assignment node without type annotation.
        """
        return convert_ann_assign_to_assign(node)

def remove_type_hints_from_body(function_node: ast.FunctionDef) -> None:
    """Remove type hints from the body statements of a function.
    
    This function applies the FastRemoveTypeHints transformer to remove
    annotated assignments from function body statements.
    
    Args:
        function_node: The function AST node to process.
    """
    transformer = FastRemoveTypeHints()
    transformer.visit(function_node)

def convert_to_py27(function_node: ast.FunctionDef) -> None:
    """Convert a function AST node to Python 2.7 compatible format.
    
    This function removes all type annotations from a function definition,
    including return type annotations, parameter type annotations, and
    type hints within the function body to ensure Python 2.7 compatibility.
    
    Args:
        function_node: The function AST node to convert to Python 2.7 format.
    """
    # Strip type hints for Python 2 compatibility
    # Remove return type annotation
    function_node.returns = None
    
    # Remove argument type annotations
    for arg in function_node.args.args:
        arg.annotation = None
    
    # Remove keyword-only argument type annotations
    for arg in function_node.args.kwonlyargs:
        arg.annotation = None
    
    # Remove vararg type annotation (*args)
    if function_node.args.vararg:
        function_node.args.vararg.annotation = None
    
    # Remove kwarg type annotation (**kwargs)  
    if function_node.args.kwarg:
        function_node.args.kwarg.annotation = None
    
    # Remove type hints from function body
    remove_type_hints_from_body(function_node)

def extract_function_info(func: Callable[..., Any]) -> FunctionInfo:
    """Parse function source code and extract name, body statements, and argument list.
    
    This function uses AST parsing to extract function information from the source code
    of a callable Python function. It removes decorators and provides the clean function
    definition along with parsed components.
    
    Args:
        func: A callable Python function to analyse.
        
    Returns:
        FunctionInfo: Object containing function name, body code, and argument names.
        
    Raises:
        ValueError: If the input is not a function or cannot be parsed.
    """
    
    source_code = inspect.getsource(func)
    # Remove common leading whitespace to handle functions defined with indentation
    source_code = textwrap.dedent(source_code)
    tree: ast.Module = ast.parse(source_code)
    
    # Check if first node exists and is a function
    if not tree.body:
        raise ValueError(f"Given input is not a function\ninput:{source_code}")
    
    first_node = tree.body[0]
    if not isinstance(first_node, ast.FunctionDef):
        raise ValueError(f"Given input is not a function\ninput:{source_code}")
    
    # Extract function blob without decorator
    first_node.decorator_list.clear()
    
    # Extract blob in python 3 format
    blob:str = ast.unparse(first_node)

    # Extract function name
    function_name = first_node.name

    # Extract body statements
    body_nodes = first_node.body
    
    # Convert back to source code
    body = ""
    for stmt in body_nodes:
        body += ast.unparse(stmt) + "\n"

    # Extract function arguments
    args: list[str] = []
    for arg in first_node.args.args:
        args.append(arg.arg)
        arg.type_comment
    
    convert_to_py27(first_node)
    blob_py27:str = ast.unparse(first_node)

    body_py27 = ""
    for stmt in body_nodes:
        body_py27 += ast.unparse(stmt) + "\n"

    return FunctionInfo(
        blob=blob,
        blob_py27=blob_py27,
        name=function_name,
        body=body.strip(),
        body_py27=body_py27,
        args=args
    )

P = ParamSpec('P')
T = TypeVar('T')

@dataclass
class TypedBlob(Generic[T]):
    blob: dict[str,str]
    return_type: Type[T]

class D3Function(Generic[P, T]):
    """Wrapper class for Python functions to be executed in Designer environment.
    
    This class transforms regular Python functions into Designer plugin compatible functions
    that can be registered as modules and executed remotely. It preserves function metadata
    and provides methods for generating execution blobs and registration data.
    """

    _available_packages: DefaultDict[str, set[str]] = defaultdict(set)
    _available_d3functions: DefaultDict[str, set["D3Function"]] = defaultdict(set)
    _registered_ipaddr:str = "localhost"

    def __init__(self, module_name: str, timeout_ms: float|None, func: Callable[P, T]):
        """Initialise a D3Function wrapper around a Python function.
        
        Args:
            module_name: Name of the module to register this function under. 
                        Empty string means standalone function execution.
            func: The Python function to wrap for D3 execution.
        """
        self._module_name: str = module_name
        self._timeout_ms: float|None = timeout_ms
        self._function: Callable[P, T] = func
        self._function_info: FunctionInfo = extract_function_info(func)
        self._is_module_function:bool = len(module_name) > 0
        
        # Update wrapper to preserve function metadata for IDE
        functools.update_wrapper(self, func)

        # Add this function into available_d3_functions
        D3Function._available_d3functions[module_name].add(self)

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> T:
        return self._function(*args, **kwargs)
    
    def __getattr__(self, name: str) -> Any:
        """Proxy attribute access to the original function for IDE support.
        
        Args:
            name: The attribute name to retrieve from the wrapped function.
            
        Returns:
            The attribute value from the wrapped function.
        """
        return getattr(self._function, name)
    
    def __hash__(self) -> int:
        """Used to uniquely register d3function in D3Function._available_d3functions. 
        Function name in python is unique, so we can function name as uid.
        
        Returns:
            Hash value of the function name.
        """
        return hash(self.name)
    
    def __eq__(self, other) -> bool:
        """Used to uniquely register d3function in D3Function._available_d3functions. 
        Function name in python is unique, so we can function name as uid.
        
        Returns:
            True if both are D3Functions with the same name, False otherwise.
        """
        if not isinstance(other, D3Function):
            return False
        return self.name == other.name

    @staticmethod
    def get_module_register_blob(module_name:str):
        """Generate a registration blob for all functions in a specific module.
        
        Args:
            module_name: The name of the module to generate the blob for.
            
        Returns:
            Dictionary containing module name and all d3function registered under module.
        """
        contents_packages: str = "\n".join([pkg for pkg in D3Function._available_packages[module_name]])
        contents_functions: str = "\n\n".join([func.function_info.blob_py27 for func in D3Function._available_d3functions[module_name]])
        return {
            "moduleName": module_name,
            "contents": f"{contents_packages}\n\n{contents_functions}"
        }

    @property 
    def __signature__(self) -> inspect.Signature:
        """Expose function signature for IDE introspection.
        
        Returns:
            The signature of the wrapped function for IDE support.
        """
        return inspect.signature(self._function)
    
    @property
    def name(self) -> str:
        """Get the name of the wrapped function.
        
        Returns:
            The name of the wrapped function.
        """
        return self.function_info.name

    @property
    def module_name(self) -> str:
        """Get the module name this function is registered under.
        
        Returns:
            The module name for this function.
        """
        return self._module_name

    @property
    def function_info(self) -> FunctionInfo:
        """Get the parsed function information.
        
        Returns:
            FunctionInfo object containing parsed details about the wrapped function.
        """
        return self._function_info

    def _args_to_string(self, *args, **kwargs) -> str:
        """Convert function arguments to a string representation for D3 script generation.
        
        Returns:
            String representation of all arguments suitable for function calls.
        """
        # Convert positional args
        args_parts = [repr(arg) for arg in args]
        # Convert keyword args  
        kwargs_parts = [f"{key}={repr(value)}" for key, value in kwargs.items()]
        # Combine them
        all_parts = args_parts + kwargs_parts
        return f"{', '.join(all_parts)}"

    def _args_to_assign(self, *args, **kwargs):
        """Convert function arguments to assignment statements for standalone execution.
        
        Returns:
            String containing variable assignment statements, one per line.
        """
        args_parts = [f"{self._function_info.args[i]}={repr(arg)}" for i, arg in enumerate(args)]
        kwargs_parts = [f"{name}={repr(value)}" for name, value in kwargs.items()]
        return "\n".join(args_parts + kwargs_parts)

    def get_execute_blob(self, *args: P.args, **kwargs: P.kwargs) -> dict[str, str]:
        """Generate an execution blob for running this function in Designer.
            
        Returns:
            - **module execute blob** if @d3function was registered with module_name
            - **script execute blob** if @d3function was registered without module_name
        """
        if self._is_module_function:
            return {
                "moduleName": self._module_name,
                "script": f"return {self._function_info.name}({self._args_to_string(*args, **kwargs)})"
            }
        else:
            all_args: str = self._args_to_assign(*args, **kwargs)
            return {
                "script": f"{all_args}\n{self._function_info.body_py27}"
            }
        
    def get_typed_execute_blob(self, *args: P.args, **kwargs: P.kwargs) -> TypedBlob[T]:
        """Generate an execution blob with the return type extracted from function annotations.

        Returns:
            Tuple containing:
            - Execution blob dictionary
            - The return type class/type from the function's type hints (or Any if not annotated)
        """
        type_hints = get_type_hints(self._function)
        return_type = type_hints.get('return')
        if not return_type:
            raise RuntimeError("Invalid return type")

        return TypedBlob(
            blob = self.get_execute_blob(*args, **kwargs),
            return_type = return_type
        )
    
    def _extract_retval(self, json_data: dict) -> T:
        try:
            plugin_response = PluginResponse[T].model_validate(json_data)
            return plugin_response.returnValue
        except Exception as e:
            status: dict = json_data.get("status", {})
            raise RuntimeError(f"""Failed to parse plugin response: {e}
Designer API error:
- code      : {status.get("code")}
- message   : {status.get("message")}
- details   : {status.get("details")}
- d3Log     : {json_data.get("d3Log")}
- pythonLog : {json_data.get("pythonLog")}
- retVal    : {json_data.get("returnValue")}
""")

    def raise_plugin_error(self, response_text: str) -> None:
        status: PluginStatus|None = None
        try:
            status = PluginStatus.model_validate(
                json.loads(response_text).get("status"))
        except Exception:
            pass
        if not status:
            # Failed to parse plugin error status
            # Don't raise
            return None
        raise PluginError(status=status)

    def execute(self, *args: P.args, **kwargs: P.kwargs) -> T:
        """Execute this function remotely on a D3 Designer instance.
        
        This method sends the function and its arguments to the registered Designer
        instance for remote execution, then returns the parsed result.
        
        Args:
            *args: Positional arguments to pass to the function.
            **kwargs: Keyword arguments to pass to the function.
            
        Returns:
            The return value from the remote function execution.
            
        Raises:
            RuntimeError: If the HTTP request fails, Designer returns an error,
                         or the return value is empty/invalid.
        """
        response: requests.Response = requests.post(
            url=f"http://{D3Function._registered_ipaddr}/{D3_PLUGIN_ENDPOINT}", 
            json=self.get_execute_blob(*args, **kwargs),
            timeout= self._timeout_ms / 1000.0 if self._timeout_ms else None
        )
        if not response.ok:
            if response.status_code == 500:
                self.raise_plugin_error(response.text)
            raise RuntimeError(f"HTTP error {response.status_code}: { response.text}")
        
        data: dict = response.json()
        return self._extract_retval(data)
    
    async def aexecute(self, *args: P.args, **kwargs: P.kwargs) -> T:
        """Asynchronously execute this function remotely on a D3 Designer instance.
        
        This method sends the function and its arguments to the registered Designer
        instance for remote execution, then returns the parsed result.
        
        Args:
            *args: Positional arguments to pass to the function.
            **kwargs: Keyword arguments to pass to the function.
            
        Returns:
            The return value from the remote function execution.
            
        Raises:
            RuntimeError: If the HTTP request fails, Designer returns an error,
                         or the return value is empty/invalid.
        """
        async with aiohttp.ClientSession() as session:
            url: str=f"http://{D3Function._registered_ipaddr}/{D3_PLUGIN_ENDPOINT}"
            async with session.post(
                url,
                json=self.get_execute_blob(*args, **kwargs),
                timeout=aiohttp.ClientTimeout(self._timeout_ms) if self._timeout_ms else None
            ) as response:
                if not response.ok:
                    error_text = await response.text()
                    if response.status == 500:
                        self.raise_plugin_error(error_text)
                    raise RuntimeError(f"HTTP error {response.status}: {error_text}")
                data = await response.json()
                return self._extract_retval(data)


###############################################################################
# d3function API
def d3function(module_name: str = "", timeout_ms: float|None = None) -> Callable[[Callable[P, T]], D3Function[P, T]]:
    """Decorator to wrap a Python function for D3 Designer execution.
    
    This decorator transforms a regular Python function into a D3Function that can be
    registered with D3 Designer and executed remotely.
    
    Args:
        module_name: Optional module name to register the function under. 
                    If empty, the function will be treated as standalone script and won't be registered.
                    
    Returns:
        A decorator function that wraps the target function in a D3Function.
        
    Example:
        ```
        @d3function("my_d3module")
        def capture_image(self, cam_name: str) -> str:
            import d3
            camera = d3.resourceManager.load(
                d3.Path('objects/camera/{cam_name}.apx'),
                d3.Camera
            )
            return camera.uid
        ```
    """
    def decorator(func: Callable[P, T]) -> D3Function[P, T]:
        return D3Function(module_name, timeout_ms, func)
    return decorator

def add_packages_in_current_file(module_name: str) -> None:
    """Add all import statements from the caller's file to a D3 module's package list.

    This function scans the calling file's import statements and registers them with
    the specified module name, making those imports available when the module is
    registered with Designer. This is useful for ensuring all dependencies are included
    when deploying Python functions to D3 Designer.

    Args:
        module_name: The name of the D3 module to associate the packages with.
                    Must match the module_name used in @d3function decorator.

    Example:
        ```python
        import numpy as np

        @d3function("my_module")
        def my_function():
            return np.array([1, 2, 3])

        # Register all imports in the file (numpy)
        add_packages_in_current_file("my_module")
        ```
    """
    # caller_stack is 2, 1 for this, 1 for caller of this function.
    packages: list[str] = find_packages_in_current_file(2)
    D3Function._available_packages[module_name].update(packages)

def register_module_d3functions(ipaddr: str, module_name: str) -> tuple[bool, str]:
    """Register all d3function in a module with a Designer instance.
    
    Args:
        ipaddr: IP address of the Designer instance.
        module_name: Name of the module to register.
        
    Returns:
        Tuple containing success status and error message (empty if successful).
    """
    # function with no module shouldn't be registered
    if len(module_name) == 0:
        return (True, "")
    
    try:
        response = requests.post(
            url=f"http://{ipaddr}/api/session/python/registermodule", 
            json=D3Function.get_module_register_blob(module_name)
        )
        return (response.ok, "")
    except Exception as e:
        return (False, str(e))

async def aregister_module_d3functions(ipaddr: str, module_name: str) -> tuple[bool, str]:
    """Asynchronously register all d3function in a module with a Designer instance.
    
    Args:
        ipaddr: IP address of the Designer instance.
        module_name: Name of the module to register.
        
    Returns:
        Tuple containing success status and error message (empty if successful).
    """
    # function with no module shouldn't be registered
    if len(module_name) == 0:
        return (True, "")
    
    try:
        url=f"http://{ipaddr}/api/session/python/registermodule"
        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=D3Function.get_module_register_blob(module_name)) as response:
                return (response.ok, "")
    except Exception as e:
        return (False, str(e))

def register_all_d3functions(ipaddr:str) -> dict[str, tuple[bool, str]]:
    """Register all available d3function across all modules with a Designer instance.
    If d3function was registered without module_name, it won't be registered. 
    
    Args:
        ipaddr: IP address of the Designer instance.
        
    Returns:
        Dictionary mapping module names to registration results (success status and error message).
    """
    responses: dict[str, tuple[bool, str]] = {}
    D3Function._registered_ipaddr = ipaddr
    for module_name in D3Function._available_d3functions.keys():
        responses[module_name] = register_module_d3functions(ipaddr, module_name)
    return responses

async def aregister_all_d3functions(ipaddr:str) -> dict[str, tuple[bool, str]]:
    """Asynchronously register all available d3function across all modules with a Designer instance.
    If d3function was registered without module_name, it won't be registered.
    
    Args:
        ipaddr: IP address of the Designer instance.
        
    Returns:
        Dictionary mapping module names to registration results (success status and error message).
    """
    responses: dict[str, tuple[bool, str]] = {}
    D3Function._registered_ipaddr = ipaddr
    for module_name in D3Function._available_d3functions.keys():
        responses[module_name] = await aregister_module_d3functions(ipaddr, module_name)
    return responses

def get_all_d3functions() -> list[tuple[str, str]]:
    """Retrieve all available d3function as module_name-function_name pairs.
    
    Returns:
        List of tuples containing (module_name, function_name) for all registered D3 functions.
    """
    module_function_pairs: list[tuple[str, str]] = []
    for module_name, funcs in D3Function._available_d3functions.items():
        module_function_pairs += [(module_name, func.function_info.name) for func in funcs]
    return module_function_pairs


def get_all_modules() -> list[str]:
    """Retrieve name of all module registered with @d3function decorator
    
    Returns:
        List of module names
    """
    return [module_name for module_name in D3Function._available_d3functions.keys()]
