"""D3 Plugin Models Module

This module contains all data models, type definitions, and exceptions
for the D3 plugin system, including:

- API endpoint constants
- Plugin response models (PluginStatus, PluginResponse, etc.)
- Plugin exceptions (PluginException)
- Type definitions for plugin execution (TypedBlob)
"""

import json
import traceback
from dataclasses import dataclass
from typing import Any, Generic, TypeVar

import typing_extensions
from pydantic import BaseModel, Field, TypeAdapter, field_validator


###############################################################################
# Plugin endpoint constants
D3_PLUGIN_ENDPOINT = "api/session/python/execute"
D3_PLUGIN_MODULE_REG_ENDPOINT = "api/session/python/registermodule"


def get_plugin_endpoint_url(hostname: str, port: int) -> str:
    """Get the full URL for the plugin execution endpoint."""
    return f"http://{hostname}:{port}/{D3_PLUGIN_ENDPOINT}"


def get_plugin_module_register_url(hostname: str, port: int) -> str:
    """Get the full URL for the module registration endpoint."""
    return f"http://{hostname}:{port}/{D3_PLUGIN_MODULE_REG_ENDPOINT}"


###############################################################################
# Plugin response types
class PluginStatusDetail(BaseModel):
    """Detail information for plugin status errors."""

    type_url: str
    value: str


class PluginStatus(BaseModel):
    """Status information from plugin API calls."""

    code: int = Field(description="Return code of plugin API call. 0 if good.")
    message: str = Field(description="Message from plugin API call.")
    details: list[PluginStatusDetail]


RetType = typing_extensions.TypeVar("RetType", default=Any)
RetCastType = TypeVar("RetCastType")


@dataclass
class PluginException(Exception):
    """Exception raised when plugin execution fails.

    Attributes:
        status: The status information from the failed plugin call
        d3Log: D3 Designer console log output
        pythonLog: Python-specific log output
    """

    status: PluginStatus
    d3Log: str | None = None
    pythonLog: str | None = None

    _traceback_str: str | None = None
    _str: str | None = None

    def __post_init__(self):
        # Capture current stack trace if not already provided
        if self._traceback_str is None:
            self._traceback_str = "".join(traceback.format_stack()[:-1])

    def __str__(self) -> str:
        if self._str is None:
            details_str = ""
            if self.status.details:
                details_list = "\n".join(
                    [f"  - {d.type_url}: {d.value}" for d in self.status.details]
                )
                details_str = f"\nDetails    :\n{details_list}"
            self._str = "\n".join(
                [
                    Exception.__str__(self),
                    f"PluginError: (code {self.status.code}){details_str}",
                    f"d3Log      : {self.d3Log}",
                    f"pythonLog  : {self.pythonLog}",
                    f"Traceback  : {self._traceback_str.strip() if self._traceback_str else ''}",
                ]
            )
        return self._str


class PluginResponse(BaseModel, Generic[RetType]):
    """Response from a plugin API call.

    Attributes:
        status: Status of the plugin API call
        d3Log: D3 Designer console log during execution
        pythonLog: Pure Python output (print statements, warnings)
        returnValue: The return value from the plugin execution
    """

    status: PluginStatus = Field(description="Status of plugin API call.")
    d3Log: str | None = Field(
        default=None,
        description="The D3 log field captures the console log for the time the Python script is executing, recording any output generated by running a Python command, including the time taken to execute the Python command. As this captures the Designer console output, it is possible other threads may write to this output during this period causing additional irrelevant output.",
    )
    pythonLog: str | None = Field(
        default=None,
        description="This output field is the pure Python output, recording any print statements or warnings occurring during the execution of the script. This output will also appear in the d3Log field, however, it may be mixed with other application output.",
    )
    returnValue: RetType = Field(description="Return value of python plugin execution")

    @field_validator("returnValue", mode="before")
    @classmethod
    def parse_returnValue(cls, v):
        if isinstance(v, str):
            if v == "null":
                return None
            else:
                return json.loads(v)
        return v

    def returnCastValue(self, castType: type[RetCastType]) -> RetCastType:
        """
        Validate and return the typed return value.

        Args:
            castType: The type to validate and cast the return value to.

        Returns:
            The validated return value as the specified type.

        Raises:
            ValidationError: If the return value cannot be validated as the specified type.
        """
        adapter = TypeAdapter(castType)
        return adapter.validate_python(self.returnValue)


class PluginError(PluginResponse[None]):
    """Error variant of PluginResponse when execution fails."""

    returnValue: None = Field(
        default=None, description="When failed to get PluginResponse, return value will not exist"
    )


###############################################################################
# Typed execution blob
@dataclass
class TypedBlob(Generic[RetType]):
    """Type-safe execution blob for plugin calls.

    This dataclass packages together the execution blob, expected return type,
    and module name for type-safe plugin execution.

    Attributes:
        blob: The execution blob dictionary (script, moduleName, etc.)
        return_type: The expected return type of the execution
        module_name: The name of the module this execution belongs to
    """

    blob: dict[str, str]
    return_type: type[RetType]
    module_name: str
